name: Process Uploaded Videos

on:
  issues:
    types: [opened]

jobs:
  process_video:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    - run: pip install -r requirements.txt
        
    - name: Process uploaded video
      run: |
        python extract_issue.py ${{ github.event.issue.number }} "${{ github.event.issue.body }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
